# Generated by Django 4.0.6 on 2022-08-29 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogo_dia_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='dia_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 19, 29, 5, 953554, tzinfo=utc)),
        ),
    ]
